server:
  port: '8081'
  servlet:
    context-path: /buyAny/v1
  error:
    include-message: always

logging:
  level:
    org.springframework.security: TRACE

jwt:
  auth:
    converter:
      resource-id: buy-any
      principal-attribute: preferred_username

# MySQL Databse
spring:
  security:
    oauth2:
#      client:
#        registration:
#          keycloak-login:
#            provider: keycloak
#            client-id: buy-any
#            client-secret: 5GTyJPKfFCfrktGAFnr6rYtpFqsXDV8n
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/auth/realms/BuyAny
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/BuyAny
          #jwk-set-uri: http://localhost:8080/auth/realms/BuyAny/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3308/buyany
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


#keycloak
#keycloak:
#  auth-server-url: http://localhost:8080/auth
#  realm: buyany
#  resource: buyany-client
#  public-client: true
#  bearer-only: true
#  use-resource-role-mappings: true
#  ssl-required: external
#  credentials:
#    principal-attribute: preferred_username
#    provider: secret